const $ = (selector, parent = document) => parent.querySelector(selector);
const $$ = (selector, parent = document) => parent.querySelectorAll(selector);

export const DOM = {
  canvas: {
    el: $("canvas"),
    overlay: $(".canvas-overlay"),
    controlLayer: $(".canvas-control-layer"),
    ctx: $("canvas").getContext("2d", { willReadFrequently: true }),
  },
  ui: {
    settingsForm: $(".settings"),
    showOriginalInput: $("#show-original"),
    showGridInput: $("#show-grid"),
    pixelatedModeToggle: $("#pixelated-mode-toggle"),
    aside: $("aside"),
    total: $(".total"),
    totalTime: $(".total-time"),
    totalTimeWithFlag: $(".total-time-with-flag"),
    resultImage: $(".result-image"),
    aboutBtn: $(".about-btn"),
    downloadBtn: $(".download-btn"),
    uploadBtn: $("#upload-btn"),
    processingProgress: $(".processing-progress"),
    progressPercentage: $(".progress-percentage"),
    progressEta: $(".progress-eta"),
    zoom: {
      inBtn: $(".zoom-in"),
      outBtn: $(".zoom-out"),
      input: $("#zoom"),
    },
    palette: {
      dropdown: $(".palette-dropdown"),
      optionsContainer: $(".palette-dropdown .dropdown-options-container"),
      basicList: $(".palette.basic"),
      lockedList: $(".palette.locked"),
      customList: $(".palette.custom"),
      selectAllBtn: $(".select-all-btn"),
      unselectAllBtn: $(".unselect-all-btn"),
      saveBtn: $(".palette-form-group .save-palette-btn"),
      resetBtn: $(".palette-form-group .reset-btn"),
    },
    methodDropdown: $(".method-dropdown"),
    settingsResetBtn: $(".settings-form-group .reset-btn"),
    sizeBtns: $$(".size-btn"),
  },
  dialog: {
    about: {
      el: $(".about-dialog"),
      cancelBtn: $(".about-dialog .cancel-btn"),
    },
    download: {
      el: $(".download-dialog"),
      fileName: $(".file-name"),
      imageSize: $(".image-size"),
      confirmBtn: $(".download-dialog .confirm-btn"),
      cancelBtn: $(".download-dialog .cancel-btn"),
    },
    terrainColor: {
      el: $(".terrain-color-dialog"),
      confirmBtn: $(".terrain-color-dialog .confirm-btn"),
      cancelBtn: $(".terrain-color-dialog .cancel-btn"),
      inputs: $$(".terrain-color-options-container input"),
      showBgCheckbox: $("#show-terrain-bg"),
      noneOption: $("#terrain-none"),
    },
    addColor: {
      el: $(".add-color-dialog"),
      form: $(".add-color-form"),
      confirmBtn: $(".add-color-dialog .confirm-btn"),
      cancelBtn: $(".add-color-dialog .cancel-btn"),
      tabSingle: $("#add-color-tab-single"),
      tabList: $("#add-color-tab-list"),
      textarea: $(".add-color-list textarea"),
      previewSingle: $(".add-color-single .color-preview"),
      previewContainer: $(".add-color-dialog .color-preview-container"),
      alert: $(".add-color-alert"),
      inputR: $("#add-color-input-r"),
      inputG: $("#add-color-input-g"),
      inputB: $("#add-color-input-b"),
      inputHex: $("#add-color-input-hex"),
      inputName: $("#add-color-input-name"),
      loaderContainer: $(".color-text-loader-container"),
    },
    savePalette: {
      el: $(".save-palette-dialog"),
      form: $(".save-palette-form"),
      previewContainer: $(".save-palette-dialog .color-preview-container"),
      alert: $(".save-palette-alert"),
      nameInput: $("#save-palette-name-input"),
      colorCount: $(".save-palette-color-count"),
      confirmBtn: $(".save-palette-dialog .confirm-btn"),
      cancelBtn: $(".save-palette-dialog .cancel-btn"),
    },
  },
};
