export const state = {
  brightness: null,
  contrast: null,
  saturation: null,
  dither: null,
  aspectRatio: 1,
  width: null,
  height: null,
  zoom: null,
  startPosition: [0, 0],
  movedPosition: [0, 0],
  position: [0, 0],
  mark: null,
  dragging: false,
  startTouchDistance: 0,
  startZoom: 0,
  currentTouches: [],
  paletteData: {},
  paletteName: "WPlace",
  palette: null,
  colorTexts: new Map(),
  fileName: null,
  image: null,
  adjusted: null,
  resized: null,
  dithered: null,
  showOriginal: false,
  showGrid: false,
  showTerrainBg: true,
  pickedColor: null,
  colorsToAdd: [],
  method: "rgb",
  workers: {
    adjust: { instance: null, isProcessing: false },
    dither: { instance: null, isProcessing: false },
  },
  isPixelMode: false,
};
