export const state = {
  brightness: null,
  contrast: null,
  saturation: null,
  dither: null,
  aspectRatio: 1,
  width: null,
  height: null,
  zoom: null,
  startPosition: [0, 0],
  position: [0, 0],
  currentPosition: [0, 0],
  isDragging: false,
  touchStartDistance: 0,
  touchStartZoom: 0,
  currentTouches: [],
  palette: null,
  fileName: null,
  image: null,
  adjusted: null,
  resized: null,
  dithered: null,
  showOriginal: false,
  method: "rgb",
  workers: {
    adjust: { instance: null, isProcessing: false },
    dither: { instance: null, isProcessing: false },
  },
};
